# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multipal analyst choice.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(646, 590)
        Dialog.setStyleSheet("\n"
"/*\n"
"ABOUT\n"
"============================================================================================================\n"
"version 2.05\n"
"QT theme (stylesheet) specially developed for FreeCAD (http://www.freecadweb.org/).\n"
"It might work with other software that uses QT styling.\n"
"\n"
"\n"
"LICENSE\n"
"============================================================================================================\n"
"Copyright (c) 2016 Pablo Gil Fern?ndez\n"
"\n"
"This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.\n"
"To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.\n"
"\n"
"\n"
"INSTALLATION\n"
"============================================================================================================\n"
"1) Place the .qss files and /images/ folder in the path that fits your OS:\n"
"    OSX = /Users/[YOUR_USER_NAME]/Library/Preferences/FreeCAD/Gui/Stylesheets/\n"
"    WINDOWS = C:/[INSTALLATION_PATH]/FreeCAD/data/Gui/Stylesheets/\n"
"    LINUX = /home/[YOUR_USER_NAME]/.FreeCAD/Gui/Stylesheets/\n"
"\n"
"2) In order to display correctly images:\n"
"    2.1) FreeCAD 0.16 (development builds newer than commit 5b3d50a): that\'s it, you are done!\n"
"\n"
"    2.2) FreeCAD 0.15: Images used in the theme need ABSOLUTE paths to be found by FreeCAD, so you should search the string \"qss:images\" (without \"\") and replace with the real path of your computer. It should be done with all the .qss files you want to install-use\n"
"        find = qss:images\n"
"        replace = /Users/myName/Library/Preferences/FreeCAD/Gui/Stylesheets/images\n"
"\n"
"\n"
"CUSTOMIZATION\n"
"============================================================================================================\n"
"If you would like to change the overall look/style of the theme, just find and replace following colors in the whole file:\n"
"    BACKGROUND (darker to ligher)\n"
"        black\n"
"        #505050\n"
"        #6e6e6e\n"
"        #828282\n"
"        #a2a2a0\n"
"        #b6b6b6\n"
"        #c8c8c8\n"
"        #c3c3c3\n"
"        #d2d2d2\n"
"        #dcdcdc\n"
"        #e0e0e0\n"
"        #e6e6e6\n"
"        #f0f0f0\n"
"        #f5f5f5 = main background color\n"
"        white\n"
"\n"
"    SELECTION (darker to lighter)\n"
"        #1b3774\n"
"        #2053c0\n"
"        #3874f2\n"
"        #5e90fa = main selection color\n"
"        #6f9efa = used to build QSpinBox up and down buttons, it\'s used as color in the middle\n"
"        #7cabf9\n"
"        #adc5ed\n"
"        #cbd8e6\n"
"\n"
"\n"
"\n"
"\n"
"KNOWN BUGS and TO DO\n"
"============================================================================================================\n"
"    - please, follow the link to get updated information: http://forum.freecadweb.org/viewtopic.php?f=10&t=12417\n"
"*/\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Reset elements\n"
"==================================================================================================*/\n"
"/* Reseting everything helps to unify styles across different operating systems */\n"
"* {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"    border-style: none;\n"
"    border-image: none;\n"
"    outline: 0;\n"
"}\n"
"\n"
"/* specific reset for elements inside QToolBar */\n"
"QToolBar * {\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Main window\n"
"==================================================================================================*/\n"
"QMainWindow,\n"
"QDialog,\n"
"QDockWidget,\n"
"QToolBar  {\n"
"    background-color: #f5f5f5; /* main background color */\n"
"}\n"
"\n"
"QMdiArea {\n"
"    background-image: url(qss:images/background_freecad.png);\n"
"    background-position: center center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"MENUS\n"
"==================================================================================================*/\n"
"QMenuBar,\n"
"QMenuBar::item {\n"
"    color: black;\n"
"    background-color: #f5f5f5; /* main background color */\n"
"}\n"
"\n"
"QMenu,\n"
"QMenu::item {\n"
"    color: black;\n"
"    background-color: #f5f5f5; /* main background color */\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"QMenuBar::item:selected,\n"
"QMenuBar::item:pressed,\n"
"QMenu::item:selected,\n"
"QMenu::item:pressed {\n"
"    color: white;\n"
"    background-color: #5e90fa;\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    image:url(qss:images/right_arrow_dark.png);\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QMenu::right-arrow:selected {\n"
"    image:url(qss:images/right_arrow_lighter.png);\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 2px 16px 2px 26px; /* make room for icon at left */\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::icon {\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: rgba(0,0,0,30);\n"
"    margin: 6px 4px;\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"    color: white;\n"
"}\n"
"\n"
"/* Fix for elements inside a drop-down menu */\n"
"QMenu QRadioButton,\n"
"QMenu QCheckBox,\n"
"QMenu QPushButton,\n"
"QMenu QToolButton {\n"
"    color: black; /* same as regular QRadioButton and QCheckBox */\n"
"}\n"
"\n"
"QMenu QRadioButton:hover,\n"
"QMenu QCheckBox:hover,\n"
"QMenu QPushButton:hover,\n"
"QMenu QToolButton:hover,\n"
"QMenu QPushButton:pressed,\n"
"QMenu QToolButton:pressed,\n"
"QMenu QPushButton:selected,\n"
"QMenu QToolButton:selected {\n"
"    color: white;\n"
"    background-color: #5e90fa; /* same as QMenu::item:selected and QMenu::item:pressed */\n"
"}\n"
"\n"
"QMenu QRadioButton:disabled,\n"
"QMenu QCheckBox:disabled {\n"
"    color: #6e6e6e;\n"
"}\n"
"\n"
"QMenu QRadioButton::indicator:disabled,\n"
"QMenu QCheckBox::indicator:disabled {\n"
"    color: #6e6e6e;\n"
"    background-color: transparent;\n"
"    border: 1px solid #6e6e6e;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tool bar\n"
"==================================================================================================*/\n"
"QToolBar {\n"
"    border: none;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QToolBar::handle:top,\n"
"QToolBar::handle:bottom,\n"
"QToolBar::handle:horizontal {\n"
"    background-image: url(qss:images/Hmovetoolbar_dark.png);\n"
"    width: 10px;\n"
"    margin: 4px 2px;\n"
"    background-position: top right;\n"
"    background-repeat: repeat-y;\n"
"}\n"
"\n"
"QToolBar::handle:left,\n"
"QToolBar::handle:right,\n"
"QToolBar::handle:vertical {\n"
"    background-image: url(qss:images/Vmovetoolbar_dark.png);\n"
"    height: 10px;\n"
"    margin: 2px 4px;\n"
"    background-position: left bottom;\n"
"    background-repeat: repeat-x;\n"
"}\n"
"\n"
"QToolBar::separator:top,\n"
"QToolBar::separator:bottom,\n"
"QToolBar::separator:horizontal {\n"
"    width: 1px;\n"
"    margin: 6px 4px;\n"
"    background-color: rgba(0,0,0,30);\n"
"}\n"
"\n"
"QToolBar::separator:left,\n"
"QToolBar::separator:right,\n"
"QToolBar::separator:vertical {\n"
"    height: 1px;\n"
"    margin: 4px 6px;\n"
"    background-color: rgba(0,0,0,30);\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Group box\n"
"==================================================================================================*/\n"
"QGroupBox {\n"
"    color: rgba(0,0,0,120);\n"
"    border:1px solid rgba(0, 0, 0, 20); /* lighter than its own border-color */;\n"
"    border-radius: 3px;\n"
"    margin-top: 10px;\n"
"    padding: 6px;\n"
"    background-color: rgba(255, 255, 255, 15);\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    top: -8px;\n"
"    left: 12px;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tooltip\n"
"==================================================================================================*/\n"
"QToolTip {\n"
"    color: white;\n"
"    background-color: #828282;\n"
"    /*opacity: 90%; doesn\'t correctly work */\n"
"    padding: 4px;\n"
"    border-radius: 3px; /* has no effect */\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Dock widget\n"
"==================================================================================================*/\n"
"QDockWidget {\n"
"    color: rgba(0,0,0,120);\n"
"    titlebar-close-icon: url(qss:images/close_dark.png);\n"
"    titlebar-normal-icon: url(qss:images/undock_dark.png);\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"    text-align: center;\n"
"    background-color: rgba(0,0,0,10);\n"
"    border: 4px solid #f5f5f5; /* fix to simulate margin between this :title and tabs */ /* same as main background color */\n"
"    border-radius: 6px; /* bigger than normal due to previous border fix */\n"
"    padding: 4px 0px; /* also needed because of previous border fix */\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    border: none;\n"
"    background: transparent;\n"
"    border-radius: 3px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center;\n"
"}\n"
"\n"
"QDockWidget::close-button {\n"
"    right: 4px;\n"
"}\n"
"    \n"
"QDockWidget::float-button {\n"
"    right: 22px;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover {\n"
"    background-color: rgba(0,0,0,15);\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed,\n"
"QDockWidget::float-button:pressed {\n"
"    background-color: rgba(0,0,0,30);\n"
"}\n"
"\n"
"/* fix for Python Console (probably there is a smarter way to arrive to it) */\n"
"QDockWidget > QFrame {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #c3c3c3;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Progress bar\n"
"==================================================================================================*/\n"
"QProgressBar,\n"
"QProgressBar:horizontal {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,10);\n"
"    text-align: center;\n"
"    border: 1px solid rgba(0,0,0,80);\n"
"    padding: 1px;\n"
"    border-radius: 3px;\n"
"}\n"
"QProgressBar::chunk,\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Scroll\n"
"==================================================================================================*/\n"
"QAbstractScrollArea {\n"
"    border-radius: 2px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractScrollArea::corner {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: transparent;\n"
"    height: 15px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgba(0,0,0,80);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgba(0,0,0,100);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    min-width: 5px;\n"
"    border-radius: 3px;\n"
"    margin: 4px 15px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    margin: 1px 3px 0px 3px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(qss:images/left_arrow_dark.png);\n"
"    width: 6px;\n"
"    height: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    margin: 1px 3px 0px 3px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(qss:images/right_arrow_dark.png);\n"
"    width: 6px;\n"
"    height: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover,\n"
"QScrollBar::sub-line:horizontal:on {\n"
"    border-image: url(qss:images/left_arrow_darker.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,\n"
"QScrollBar::add-line:horizontal:on {\n"
"    border-image: url(qss:images/right_arrow_darker.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: transparent;\n"
"    width: 15px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    min-height: 5px;\n"
"    border-radius: 3px;\n"
"    margin: 15px 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    margin: 3px 0px 3px 1px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(qss:images/up_arrow_dark.png);\n"
"    height: 6px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    margin: 3px 0px 3px 1px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(qss:images/down_arrow_dark.png);\n"
"    height: 6px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::sub-line:vertical:on {\n"
"    border-image: url(qss:images/up_arrow_darker.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover,\n"
"QScrollBar::add-line:vertical:on {\n"
"    border-image: url(qss:images/down_arrow_darker.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tab bar\n"
"==================================================================================================*/\n"
"QTabWidget::pane {\n"
"    background-color: transparent; /* temporal (transparent background) */ /* tab content background color */\n"
"    position: absolute;\n"
"}\n"
"\n"
"QTabWidget::pane:top {\n"
"    top: -1px;\n"
"    border-top: 1px solid #d2d2d2;\n"
"}\n"
"\n"
"QTabWidget::pane:bottom {\n"
"    bottom: -1px;\n"
"    border-bottom: 1px solid #d2d2d2;\n"
"}\n"
"\n"
"QTabWidget::pane:left {\n"
"    right: -1px;\n"
"    border-right: 1px solid #d2d2d2;\n"
"}\n"
"\n"
"QTabWidget::pane:right {\n"
"    left: -1px;\n"
"    border-left: 1px solid #d2d2d2;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top,\n"
"QTabWidget::tab-bar:bottom {\n"
"    left: 10px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left,\n"
"QTabWidget::tab-bar:right {\n"
"    top: 10px;\n"
"}\n"
"\n"
"QTabBar {\n"
"    qproperty-drawBase: 0; /* important */\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Workaround for QTabBars created from docked QDockWidgets which don\'t draw the border if not set and reseted as follows: */\n"
"QTabBar {\n"
"    border-top: 1px solid #d2d2d2;  /* set color for all QTabBars */\n"
"}\n"
"QDockWidget QTabBar {\n"
"    border-color: transparent; /* set color for all QTabBars but ones created from QDockWidget */\n"
"}\n"
"QDialog QTabBar {\n"
"    border-color: transparent; /* set color for QTabBars inside Preferences dialog */\n"
"}\n"
"/* end fix */\n"
"\n"
"QTabBar::tab {\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top,\n"
"QTabBar::tab:bottom {\n"
"    border-top-width: 4px; /* same as selected tab colored border in order to center close-button */\n"
"    border-bottom-width: 4px; /* same as selected tab colored border in order to center close-button */\n"
"    min-width: 11ex;\n"
"    margin-left: 2px;\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:left,\n"
"QTabBar::tab:right {\n"
"    border-left-width: 4px; /* same as selected tab colored border in order to center close-button */\n"
"    border-right-width: 4px; /* same as selected tab colored border in order to center close-button */\n"
"    min-height: 14ex;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #f5f5f5; /* same as tab content background color */\n"
"    border-color: #d2d2d2;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-top: 4px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5e90fa, stop:1 #3874f2); /* selection color */\n"
"    border-bottom-color: #f5f5f5; /* same as tab content background color */\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-bottom: 4px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5e90fa, stop:1 #3874f2); /* selection color */\n"
"    border-top-color: #f5f5f5; /* same as tab content background color */\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-left: 4px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #5e90fa, stop:1 #3874f2); /* selection color */\n"
"    border-right-color: #f5f5f5; /* same as tab content background color */\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-right: 4px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #5e90fa, stop:1 #3874f2); /* selection color */\n"
"    border-left-color: #f5f5f5; /* same as tab content background color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    color: rgba(0,0,0,160);\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    color: rgba(0,0,0,220);\n"
"    background-color: rgba(0,0,0,20);\n"
"}\n"
"\n"
"QTabBar::tab:first:selected {\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"    margin: 0; /* if there is only one tab, we don\'t want overlapping margins */\n"
"}\n"
"\n"
"/* hack to access Preference TabBar background */\n"
"QDialog#Gui__Dialog__DlgPreferences > QFrame QFrame {\n"
"    background-color: transparent; /* main background color (in Windows is #f5f5f5) */\n"
"}\n"
"\n"
"/* fix for previous hack that broke QTabWidget background on Windows */\n"
"QDialog#Gui__Dialog__DlgPreferences QTabWidget::pane {\n"
"    background-color: transparent; /* temporal (transparent background) */\n"
"}\n"
"\n"
"/* hack to correctly align Preferences icon list on OSX */\n"
"QDialog#Gui__Dialog__DlgPreferences > QListView {\n"
"    min-width: 130px;\n"
"}\n"
"\n"
"/* unique styles for sections inside Preferences */\n"
"QDialog#Gui__Dialog__DlgPreferences > QListView::item {\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QDialog#Gui__Dialog__DlgPreferences > QListView::item:hover {\n"
"    background-color: #dcdcdc;\n"
"}\n"
"\n"
"QDialog#Gui__Dialog__DlgPreferences > QListView::item:selected {\n"
"    color: white;\n"
"    background-color: #5e90fa;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tab bar buttons\n"
"==================================================================================================*/\n"
"/* Close button */\n"
"QTabBar::close-button {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: center right; /* only works for QT 4.6 and newer */;\n"
"    border-radius: 2px;\n"
"    background-image: url(qss:images/close_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background-color: rgba(0,0,0,20);\n"
"}\n"
"\n"
"QTabBar::close-button:pressed {\n"
"    background-color: rgba(0,0,0,30);\n"
"}\n"
"\n"
"/* Fix for lists inside Model tab */\n"
"QDockWidget QTreeView,\n"
"QDockWidget QListView,\n"
"QDockWidget QTableView {\n"
"    margin: 6px;\n"
"    border: 1px solid #c3c3c3; /* same as regular QTreeView, QListView and QTableView */\n"
"    min-height: 40px; /* neccesary in some areas of FreeCAD */\n"
"}\n"
"\n"
"/* Buttons to scroll tabs if there is not space to show all of them: */\n"
"QTabBar::scroller {\n"
"    width: 20px; /* the width of the scroll buttons */\n"
"}\n"
"\n"
"QTabBar QToolButton,\n"
"QTabBar QToolButton:hover {\n"
"    background-color: #f5f5f5; /* same as main background color */\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled {\n"
"     image: url(qss:images/right_arrow_dark.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled,\n"
"QTabBar QToolButton::right-arrow:off {\n"
"     image: url(qss:images/right_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:hover {\n"
"     image: url(qss:images/right_arrow_darker.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:enabled {\n"
"     image: url(qss:images/left_arrow_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:disabled,\n"
" QTabBar QToolButton::left-arrow:off {\n"
"     image: url(qss:images/left_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:hover {\n"
"     image: url(qss:images/left_arrow_darker.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:enabled {\n"
"     image: url(qss:images/up_arrow_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:disabled,\n"
" QTabBar QToolButton::up-arrow:off {\n"
"     image: url(qss:images/up_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:hover {\n"
"     image: url(qss:images/up_arrow_darker.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:enabled {\n"
"     image: url(qss:images/down_arrow_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:disabled,\n"
" QTabBar QToolButton::down-arrow:off {\n"
"     image: url(qss:images/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:hover {\n"
"     image: url(qss:images/down_arrow_darker.png);\n"
"}\n"
"\n"
"QTabBar::tear {\n"
"    /* default OS tear better */\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tree and list views\n"
"==================================================================================================*/\n"
"QTreeView,\n"
"QListView,\n"
"QTableView {\n"
"    background-color: #f0f0f0;\n"
"    alternate-background-color: #e6e6e6; /* related with QListView background  */\n"
"    border: 1px solid #c3c3c3; \n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa; /* should be similar to QListView::item selected background-color */\n"
"    show-decoration-selected: 1; /* make the selection span the entire width of the view */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QListView::item:hover,\n"
"QTreeView::item:hover  {\n"
"    background-color: transparent; /* fix to homogenize it on all OSs */\n"
"}\n"
"\n"
"QListView::item:selected,\n"
"QTreeView::item:selected  {\n"
"    color: white; /* should be similar to QListView selection-color */\n"
"    background-color: #5e90fa; /* should be similar to QListView selection-background-color */\n"
"    show-decoration-selected: 1; /* make the selection span the entire width of the view */\n"
"}\n"
"\n"
"/* Property Editor QTreeView (FreeCAD custom widget) */\n"
"Gui--PropertyEditor--PropertyEditor {\n"
"    gridline-color: #d2d2d2; /* same as Group header background */\n"
"}\n"
"\n"
"/* fix for column items background when a link is present */\n"
"Gui--PropertyEditor--PropertyEditor > QWidget > QFrame:focus {\n"
"    background-color: #cbd8e6; /* same as focused background color */\n"
"}\n"
"\n"
"/* hack to hide weird redundant information inside the value of a Placement cell */\n"
"Gui--PropertyEditor--PropertyEditor > QWidget > QWidget > QLabel,\n"
"Gui--PropertyEditor--PropertyEditor > QWidget > QWidget > QLabel:disabled {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* hack to hide non editable cells inside Property values */\n"
"Gui--PropertyEditor--PropertyEditor QLineEdit:read-only,\n"
"Gui--PropertyEditor--PropertyEditor QLineEdit:disabled,\n"
"Gui--PropertyEditor--PropertyEditor QAbstractSpinBox:read-only,\n"
"Gui--PropertyEditor--PropertyEditor QAbstractSpinBox:disabled {\n"
"    color: transparent;\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"    selection-color: transparent;\n"
"    selection-background-color: transparent;\n"
"}\n"
"\n"
"/* hack to disable margin inside Property values to following elements */\n"
"Gui--PropertyEditor--PropertyEditor QSpinBox,\n"
"Gui--PropertyEditor--PropertyEditor QDoubleSpinBox,\n"
"Gui--PropertyEditor--PropertyEditor QAbstractSpinBox,\n"
"Gui--PropertyEditor--PropertyEditor QLineEdit,\n"
"Gui--PropertyEditor--PropertyEditor QComboBox {\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"    padding-top: 0px;\n"
"    padding-bottom: 0px;\n"
"}\n"
"\n"
"/* reset min-height to 0px inside list views */\n"
"QTreeView > QWidget > QComboBox,\n"
"QTreeView > QWidget > QAbstractSpinBox,\n"
"QTreeView > QWidget > QSpinBox,\n"
"QTreeView > QWidget > QDoubleSpinBox,\n"
"QTreeView > QWidget > QLineEdit,\n"
"QTreeView > QWidget > QTextEdit,\n"
"QTreeView > QWidget > QTimeEdit,\n"
"QTreeView > QWidget > QDateEdit,\n"
"QTreeView > QWidget > QDateTimeEdit,\n"
"QTreeView > QWidget > Gui--ColorButton {\n"
"    min-height: 0px;\n"
"}\n"
"\n"
"/* set border-radius to 0px inside list views */\n"
"QTreeView > QWidget > QComboBox,\n"
"QTreeView > QWidget > QAbstractSpinBox,\n"
"QTreeView > QWidget > QSpinBox,\n"
"QTreeView > QWidget > QDoubleSpinBox,\n"
"QTreeView > QWidget > QLineEdit,\n"
"QTreeView > QWidget > QTextEdit,\n"
"QTreeView > QWidget > QTimeEdit,\n"
"QTreeView > QWidget > QDateEdit,\n"
"QTreeView > QWidget > QDateTimeEdit,\n"
"QTreeView > QWidget > QComboBox:drop-down,\n"
"QTreeView > QWidget > QAbstractSpinBox:up-button,\n"
"QTreeView > QWidget > QSpinBox:up-button,\n"
"QTreeView > QWidget > QDoubleSpinBox:up-button,\n"
"QTreeView > QWidget > QTimeEdit:up-button,\n"
"QTreeView > QWidget > QDateEdit:up-button,\n"
"QTreeView > QWidget > QDateTimeEdit:up-button,\n"
"QTreeView > QWidget > QAbstractSpinBox:down-button,\n"
"QTreeView > QWidget > QSpinBox:down-button,\n"
"QTreeView > QWidget > QDoubleSpinBox:down-button,\n"
"QTreeView > QWidget > QTimeEdit:down-button,\n"
"QTreeView > QWidget > QDateEdit:down-button,\n"
"QTreeView > QWidget > QDateTimeEdit:down-button,\n"
"QTreeView > QWidget > Gui--ColorButton {\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/* set focus colors to best viewing the editable fields */\n"
"QTreeView > QWidget > QComboBox:focus,\n"
"QTreeView > QWidget > QAbstractSpinBox:focus,\n"
"QTreeView > QWidget > QSpinBox:focus,\n"
"QTreeView > QWidget > QDoubleSpinBox:focus,\n"
"QTreeView > QWidget > QLineEdit:focus,\n"
"QTreeView > QWidget > QTextEdit:focus,\n"
"QTreeView > QWidget > QTimeEdit:focus,\n"
"QTreeView > QWidget > QDateEdit:focus,\n"
"QTreeView > QWidget > QDateTimeEdit:focus {\n"
"    border-color: #cbd8e6; /* same as focused background color */\n"
"    border-bottom-color: #7cabf9; /* same as focused border color */\n"
"}\n"
"\n"
"QTreeView > QWidget > QAbstractSpinBox:read-only,\n"
"QTreeView > QWidget > QSpinBox:read-only,\n"
"QTreeView > QWidget > QDoubleSpinBox:read-only,\n"
"QTreeView > QWidget > QLineEdit:read-only,\n"
"QTreeView > QWidget > QTextEdit:read-only,\n"
"QTreeView > QWidget > QTimeEdit:read-only,\n"
"QTreeView > QWidget > QDateEdit:read-only,\n"
"QTreeView > QWidget > QDateTimeEdit:read-only {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"/* Fix to correctly (not totally) draw QTextEdit on OSX at Page properties: \"Page result\", \"Template\" and \"Editable Texts\" */\n"
"Gui--PropertyEditor--PropertyEditor > QWidget > QWidget > QWidget {\n"
"    min-height: 14px;\n"
"    border-radius: 0px; /* reset */\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Header of tree and list views\n"
"==================================================================================================*/\n"
"QHeaderView {\n"
"    background-color: #c3c3c3;\n"
"    border-top-left-radius: 2px; /* 1px less than its container */\n"
"    border-top-right-radius: 2px; /* 1px less than its container */\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    border:none;\n"
"    padding: 4px 6px;\n"
"    background-color: #c3c3c3;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    padding: 4px 6px; /* left and right value similar to QHeaderView::section */\n"
"    border-right: 1px solid rgba(0,0,0,30);\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-bottom: 1px solid rgba(0,0,0,30);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #c3c3c3;\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: 1px solid rgba(0,0,0,30);\n"
"    border-bottom: 1px solid rgba(0,0,0,30);\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(qss:images/up_arrow_dark.png);\n"
"}\n"
"\n"
"QHeaderView::up-arrow:hover {\n"
"    image: url(qss:images/up_arrow_darker.png);\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    image: url(qss:images/down_arrow_dark.png);\n"
"}\n"
"\n"
"QHeaderView::down-arrow:hover {\n"
"    image: url(qss:images/down_arrow_darker.png);\n"
"}\n"
"\n"
"/* Group header inside Property Editor (FreeCAD custom widget) */\n"
"Gui--PropertyEditor--PropertyEditor {\n"
"    qproperty-groupTextColor: #828282; /* same as main background color */\n"
"    qproperty-groupBackground: #d2d2d2; /* same as item gridlines */\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Branch system for QTreeViews\n"
"==================================================================================================*/\n"
"QTreeView::branch  {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item  {\n"
"    border-image: url(qss:images/branch_vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item  {\n"
"    border-image: url(qss:images/branch_more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item  {\n"
"    border-image: url(qss:images/branch_end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings  {\n"
"    image: url(qss:images/branch_closed_dark.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed  {\n"
"    image: url(qss:images/branch_closed_dark.png);\n"
"    border-image: url(qss:images/branch_end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"    image: url(qss:images/branch_open_dark.png);\n"
"    border-image: url(qss:images/branch_more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings  {\n"
"    image: url(qss:images/branch_open_dark.png);\n"
"    border-image: url(qss:images/branch_end.png) 0;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Splitter and windows separator\n"
"==================================================================================================*/\n"
"QSplitter::handle {\n"
"    margin: 0px 11px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    background-image: url(qss:images/splitter_vertical_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    margin: 4px 2px 4px 2px;\n"
"    width: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    background-image: url(qss:images/splitter_horizontal_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    margin: 2px 4px 2px 4px;\n"
"    height: 2px;\n"
"}\n"
"\n"
"/* Similar to the splitter is the following window separator (but horizontal/vertical is on the opposite way) */\n"
"QMainWindow::separator {\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal {\n"
"    height: 2px;\n"
"    background-image: url(qss:images/splitter_horizontal_dark.png);\n"
"    margin: 4px 2px 4px 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:vertical {\n"
"    width: 2px;\n"
"    background-image: url(qss:images/splitter_vertical_dark.png);\n"
"    margin: 2px 4px 2px 4px;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Text/Python editor (macros, etc...)\n"
"==================================================================================================*/\n"
"QPlainTextEdit,\n"
"QPlainTextEdit:focus {\n"
"    background-color: #f0f0f0;\n"
"    selection-color: white;\n"
"    selection-background-color: #3874f2;\n"
"    border: 1px solid #c3c3c3;\n"
"    border-radius: 3px;\n"
"    margin: 4px;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tasks panel (custom FreeCAD class)\n"
"==================================================================================================*/\n"
"/* Action group */\n"
"QFrame[class=\"panel\"] {\n"
"    background-color: transparent; /* temporal (transparent background) */\n"
"}\n"
"\n"
"QSint--ActionGroup {\n"
"    padding: 0px; /* if not reset, it might create problems with QPushButtons and other elements */\n"
"    margin: 0px; /* if not reset, it might create problems with QPushButtons and other elements */\n"
"}\n"
"\n"
"/* Separator line */\n"
"QSint--ActionGroup QFrame[height=\"1\"],\n"
"QSint--ActionGroup QFrame[height=\"2\"],\n"
"QSint--ActionGroup QFrame[height=\"3\"],\n"
"QSint--ActionGroup QFrame[width=\"1\"],\n"
"QSint--ActionGroup QFrame[width=\"2\"],\n"
"QSint--ActionGroup QFrame[width=\"3\"] {\n"
"    border-color: rgba(0,0,0,60);\n"
"}\n"
"\n"
"/* Panel header */\n"
"QSint--ActionGroup QFrame[class=\"header\"] {\n"
"    border: none;\n"
"    background-color: #b6b6b6; /* Task Panel Header background color */\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"]:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5e90fa, stop:1 #3874f2);\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"header\"] {\n"
"    color: white; /* Task Panel Header text color */\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel {\n"
"    background-color: transparent;\n"
"    background-image: url(qss:images/down_arrow_light.png);\n"
"    background-repeat: none;\n"
"    background-position: center center;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel:hover {\n"
"    background-color: transparent;\n"
"    background-image: url(qss:images/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel[fold=\"true\"] {\n"
"    background-color: transparent;\n"
"    background-image: url(qss:images/up_arrow_light.png);\n"
"    background-repeat: none;\n"
"    background-position: center center;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel[fold=\"true\"]:hover {\n"
"    background-color: transparent;\n"
"    background-image: url(qss:images/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] {\n"
"    background-color: #e6e6e6; /* Task Panel background color */\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] > QWidget {\n"
"    background-color: #e6e6e6; /* Task Panel background color */\n"
"}\n"
"\n"
"/* Fixs for tabs inside Task Panel */\n"
"QSint--ActionGroup QFrame[class=\"content\"] QTabBar::tab:top:selected {\n"
"    border-bottom-color: #e6e6e6; /* same as Task Panel background color */\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QTabBar::tab:bottom:selected {\n"
"    border-top-color: #e6e6e6; /* same as Task Panel background color */\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QTabBar::tab:right:selected {\n"
"    border-right-color: #e6e6e6; /* same as Task Panel background color */\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QTabBar::tab:left:selected {\n"
"    border-left-color: #e6e6e6; /* same as Task Panel background color */\n"
"}\n"
"\n"
"/* Fix for buttons with icons that showed cropped (still not happy with result) */\n"
"QSint--ActionGroup QFrame[class=\"content\"] > QWidget > QPushButton {\n"
"    padding: 2px; /* bigger padding crops text and icons... */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Buttons\n"
"==================================================================================================*/\n"
"/* Common */\n"
"QComboBox,\n"
"QAbstractSpinBox,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QLineEdit,\n"
"QTextEdit,\n"
"QTimeEdit,\n"
"QDateEdit,\n"
"QDateTimeEdit {\n"
"    color: #6e6e6e;\n"
"    background-color: #e0e0e0;\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3px;\n"
"    min-width: 50px; /* it ensures the default value is correctly displayed */\n"
"    min-height: 20px; /* important to be a pair number in order to up/down buttons to be divisible by two (if not set could create a blank line in Ubuntu. Its downside is that it\'s needed to reset it (min-width: 0px) on following elements that can\'t have it such as fields inside QToolBar and inside QTreeView (Property editor) */\n"
"    padding: 1px 2px; /* temporal: could don\'t be compatible with elements inside Tree/List view */\n"
"}\n"
"\n"
"/* shifts text/number editable field to the left to make space for the up/down or drop-down buttons */\n"
"QComboBox,\n"
"QAbstractSpinBox,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QTimeEdit,\n"
"QDateEdit,\n"
"QDateTimeEdit {\n"
"    padding-right: 20px;\n"
"}\n"
"\n"
"/* when QTextEdit are no editable */\n"
"QTextEdit:!editable {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #c3c3c3;\n"
"}\n"
"\n"
"QComboBox:focus,\n"
"QAbstractSpinBox:focus,\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus,\n"
"QLineEdit:focus,\n"
"QTextEdit:focus,\n"
"QTimeEdit:focus,\n"
"QDateEdit:focus,\n"
"QDateTimeEdit:focus {\n"
"    color: black;\n"
"    border-color: #7cabf9;\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9); /* same as up/down or drop-down button color */\n"
"    background-color: #cbd8e6;\n"
"}\n"
"\n"
"QComboBox:disabled,\n"
"QAbstractSpinBox:disabled,\n"
"QSpinBox:disabled,\n"
"QDoubleSpinBox:disabled,\n"
"QLineEdit:disabled,\n"
"QTextEdit:disabled,\n"
"QTimeEdit:disabled,\n"
"QDateEdit:disabled,\n"
"QDateTimeEdit:disabled {\n"
"    color: #c3c3c3;\n"
"    background-color: #e0e0e0; /* same as enabled color */\n"
"    border-color: #e0e0e0; /* same as enabled color */\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button,\n"
"QSpinBox:up-button,\n"
"QDoubleSpinBox:up-button,\n"
"QTimeEdit:up-button,\n"
"QDateEdit:up-button,\n"
"QDateTimeEdit:up-button,\n"
"QAbstractSpinBox:down-button,\n"
"QSpinBox:down-button,\n"
"QDoubleSpinBox:down-button,\n"
"QTimeEdit:down-button,\n"
"QDateEdit:down-button,\n"
"QDateTimeEdit:down-button {\n"
"    background-color: #d2d2d2;\n"
"    subcontrol-origin: border; /* important */\n"
"    width: 20px; /* same as QComboBox ... QDateTimeEdit padding-right */\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button,\n"
"QSpinBox:up-button,\n"
"QDoubleSpinBox:up-button,\n"
"QTimeEdit:up-button,\n"
"QDateEdit:up-button,\n"
"QDateTimeEdit:up-button {\n"
"    subcontrol-position: top right;\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button,\n"
"QSpinBox:down-button,\n"
"QDoubleSpinBox:down-button,\n"
"QTimeEdit:down-button,\n"
"QDateEdit:down-button,\n"
"QDateTimeEdit:down-button {\n"
"    subcontrol-position: bottom right;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button:focus,\n"
"QSpinBox:up-button:focus,\n"
"QDoubleSpinBox:up-button:focus,\n"
"QTimeEdit:up-button:focus,\n"
"QDateEdit:up-button:focus,\n"
"QDateTimeEdit:up-button:focus {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #6f9efa, stop:1 #7cabf9);\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button:focus,\n"
"QSpinBox:down-button:focus,\n"
"QDoubleSpinBox:down-button:focus,\n"
"QTimeEdit:down-button:focus,\n"
"QDateEdit:down-button:focus,\n"
"QDateTimeEdit:down-button:focus {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #6f9efa);\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button:disabled,\n"
"QSpinBox:up-button:disabled,\n"
"QDoubleSpinBox:up-button:disabled,\n"
"QTimeEdit:up-button:disabled,\n"
"QDateEdit:up-button:disabled,\n"
"QDateTimeEdit:up-button:disabled,\n"
"QAbstractSpinBox:down-button:disabled,\n"
"QSpinBox:down-button:disabled,\n"
"QDoubleSpinBox:down-button:disabled,\n"
"QTimeEdit:down-button:disabled,\n"
"QDateEdit:down-button:disabled,\n"
"QDateTimeEdit:down-button:disabled {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow,\n"
"QSpinBox::up-arrow,\n"
"QDoubleSpinBox::up-arrow,\n"
"QTimeEdit::up-arrow,\n"
"QDateEdit::up-arrow,\n"
"QDateTimeEdit::up-arrow {\n"
"    image: url(qss:images/up_arrow_dark.png);\n"
"    top: 2px; /* fix symmetry between up and down images */\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:focus,\n"
"QSpinBox::up-arrow:focus,\n"
"QDoubleSpinBox::up-arrow:focus,\n"
"QTimeEdit::up-arrow:focus,\n"
"QDateEdit::up-arrow:focus,\n"
"QDateTimeEdit::up-arrow:focus {\n"
"    image: url(qss:images/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:off,\n"
"QSpinBox::up-arrow:off,\n"
"QDoubleSpinBox::up-arrow:off,\n"
"QTimeEdit::up-arrow:off,\n"
"QDateEdit::up-arrow:off,\n"
"QDateTimeEdit::up-arrow:off {\n"
"    image: url(qss:images/up_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:disabled,\n"
"QSpinBox::up-arrow:disabled,\n"
"QDoubleSpinBox::up-arrow:disabled,\n"
"QTimeEdit::up-arrow:disabled,\n"
"QDateEdit::up-arrow:disabled,\n"
"QDateTimeEdit::up-arrow:disabled {\n"
"    image: url(qss:images/up_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow,\n"
"QSpinBox::down-arrow,\n"
"QDoubleSpinBox::down-arrow,\n"
"QTimeEdit::down-arrow,\n"
"QDateEdit::down-arrow,\n"
"QDateTimeEdit::down-arrow {\n"
"    image: url(qss:images/down_arrow_dark.png);\n"
"    bottom: 0px; /* fix simetry between up and down images */\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:focus,\n"
"QSpinBox::down-arrow:focus,\n"
"QDoubleSpinBox::down-arrow:focus,\n"
"QTimeEdit::down-arrow:focus,\n"
"QDateEdit::down-arrow:focus,\n"
"QDateTimeEdit::down-arrow:focus {\n"
"    image: url(qss:images/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:off,\n"
"QSpinBox::down-arrow:off,\n"
"QDoubleSpinBox::down-arrow:off,\n"
"QTimeEdit::down-arrow:off,\n"
"QDateEdit::down-arrow:off,\n"
"QDateTimeEdit::down-arrow:off {\n"
"    image: url(qss:images/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:disabled,\n"
"QSpinBox::down-arrow:disabled,\n"
"QDoubleSpinBox::down-arrow:disabled,\n"
"QTimeEdit::down-arrow:disabled,\n"
"QDateEdit::down-arrow:disabled,\n"
"QDateTimeEdit::down-arrow:disabled {\n"
"    image: url(qss:images/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"/* ComboBox */\n"
"QComboBox::drop-down {\n"
"    background-color: #d2d2d2;\n"
"    subcontrol-origin: border; /* important */\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on,\n"
"QComboBox::drop-down:focus {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(qss:images/down_arrow_dark.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(qss:images/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:off,\n"
"QComboBox::down-arrow:disabled {\n"
"    image: url(qss:images/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"/* ComboBox menu */\n"
"QComboBox {\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #6e6e6e; /* same as regular QComboBox color */\n"
"    background-color: transparent;\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"    border-width: 5px 0px 5px 0px;\n"
"    border-style: solid;\n"
"    border-color: transparent;\n"
"    margin: 0px -1px 0px 0px; /* temporal: hack for Mac... try it on Windows and Linux */\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Push button\n"
"==================================================================================================*/\n"
"\n"
"\n"
"/* Fix for Expressions description QFrame that is \"broken\" with initial reset */\n"
"Gui--PropertyEditor--PropertyEditor > QWidget > QWidget > QWidget > QWidget > QFrame {\n"
"    background-color: #f5f5f5; /* main background color */\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 2px;\n"
"    padding: 2px 6px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #5e90fa;\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tool button inside QDialogs that works as QPushButtons\n"
"==================================================================================================*/\n"
"/* found under Tools -> Customize -> Macros -> Pixmap \"...\" button */\n"
"QDialog QToolButton {\n"
"    color: #6e6e6e;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.3, x2:0, y2:1, stop:0 #f5f5f5, stop:1 #e6e6e6);\n"
"    border: 1px solid #d2d2d2;\n"
"    border-bottom-color: #c3c3c3; /* simulates shadow under the button */\n"
"    padding: 0px; /* different than regular QPushButton */\n"
"    margin: 2px; /* different than regular QPushButton */\n"
"    min-height: 16px; /* same as QTabBar QPushButton min-width */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QDialog QToolButton:hover,\n"
"QDialog QToolButton:focus {\n"
"    color: white;\n"
"    border-color: #3874f2;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5e90fa, stop:1 #3874f2);\n"
"}\n"
"\n"
"QDialog QToolButton:disabled,\n"
"QDialog QToolButton:disabled:checked {\n"
"    color: #b6b6b6;\n"
"    border-color: #e6e6e6;\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QDialog QToolButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tool button inside Task Panel content that works as QPushButtons\n"
"==================================================================================================*/\n"
"/* found inside Part Design Workbench and \"make a draft on a face\" Task panel options */\n"
"QSint--ActionGroup QFrame[class=\"content\"] QToolButton {\n"
"    color: #6e6e6e;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.3, x2:0, y2:1, stop:0 #f5f5f5, stop:1 #e6e6e6);\n"
"    border: 1px solid #d2d2d2;\n"
"    border-bottom-color: #c3c3c3; /* simulates shadow under the button */\n"
"    padding: 2px 6px; /* different than regular QPushButton */\n"
"    margin: 2px; /* different than regular QPushButton */\n"
"    min-height: 16px; /* same as QTabBar QPushButton min-width */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QToolButton:hover,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QToolButton:focus {\n"
"    color: white;\n"
"    border-color: #3874f2;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5e90fa, stop:1 #3874f2);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QToolButton:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QToolButton:disabled:checked {\n"
"    color: #b6b6b6;\n"
"    border-color: #e6e6e6;\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QToolButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Radio button\n"
"==================================================================================================*/\n"
"QRadioButton::indicator:unchecked{\n"
"    color: #505050;\n"
"    background-color: rgba(0, 0, 0, 20);\n"
"    border: 1px solid #505050;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5e90fa; /* QCheckBox has the same color */\n"
"    border: 1px solid #3874f2; /* QCheckBox has the same color */\n"
"    image:url(qss:images/radiobutton_light.png);\n"
"}\n"
"\n"
"QRadioButton,\n"
"QRadioButton:disabled {\n"
"    color: #505050;\n"
"    padding: 3px;\n"
"    outline: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:pressed {\n"
"    border-color: #adc5ed;\n"
"}\n"
"\n"
"QRadioButton::indicator:disabled {\n"
"    color: #6e6e6e;\n"
"    background-color: transparent;\n"
"    border: 1px solid #6e6e6e;\n"
"}\n"
"\n"
"QRadioButton:focus {\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Checkbox\n"
"==================================================================================================*/\n"
"QCheckBox,\n"
"QCheckBox:disabled {\n"
"    color: #505050;\n"
"    padding: 3px;\n"
"    outline: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    color: #c8c8c8;\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #505050;\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius:2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:pressed,\n"
"QCheckBox::indicator:non-exclusive:checked:pressed,\n"
"QCheckBox::indicator:indeterminate:pressed,\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border-color: #adc5ed;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #5e90fa; /* QRadioButton has the same color */\n"
"    border: 1px solid #3874f2; /* QRadioButton has the same color */\n"
"    image:url(qss:images/checkbox_light.png);\n"
"}\n"
"\n"
"QCheckBox:disabled {\n"
"    color: rgba(0,0,0,40);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid rgba(0,0,0,20);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"    background-color: #5e90fa;\n"
"    border: 1px solid #3874f2;\n"
"    image: url(qss:images/checkbox_indeterminate_light.png);\n"
"}\n"
"\n"
"QCheckBox:focus {\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Checkboxs inside QListWidget and QTreeView\n"
"==================================================================================================*/\n"
"QListWidget::indicator,\n"
"QTreeView::indicator {\n"
"    color: #c8c8c8;\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #505050;\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius:2px;\n"
"}\n"
"\n"
"/* fix for QTreeView::indicator loosing its margin */\n"
"QTreeView::indicator {\n"
"    margin: 3px;\n"
"}\n"
"\n"
"QListWidget::indicator:selected,\n"
"QTreeView::indicator:selected {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QListWidget::indicator:checked:selected,\n"
"QListWidget::indicator:indeterminate:selected,\n"
"QTreeView::indicator:checked:selected,\n"
"QTreeView::indicator:indeterminate:selected {\n"
"    background-color: #7cd439; /* slighly lighter than default */\n"
"    border-color: #2053c0; /* slighly darker than default */\n"
"}\n"
"\n"
"QListWidget::indicator:pressed,\n"
"QListWidget::indicator:non-exclusive:checked:pressed,\n"
"QListWidget::indicator:indeterminate:pressed,\n"
"QListWidget::indicator:checked:pressed,\n"
"QTreeView::indicator:pressed,\n"
"QTreeView::indicator:non-exclusive:checked:pressed,\n"
"QTreeView::indicator:indeterminate:pressed,\n"
"QTreeView::indicator:checked:pressed {\n"
"    border-color: #adc5ed;\n"
"}\n"
"\n"
"QListWidget::indicator:checked,\n"
"QTreeView::indicator:checked {\n"
"    background-color: #7cd439; /* QRadioButton has the same color */\n"
"    border: 1px solid #3874f2; /* QRadioButton has the same color */\n"
"    image:url(qss:images/checkbox_light.png);\n"
"}\n"
"\n"
"QListWidget::indicator:disabled,\n"
"QTreeView::indicator:disabled {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid rgba(0,0,0,20);\n"
"}\n"
"\n"
"QListWidget::indicator:indeterminate,\n"
"QTreeView::indicator:indeterminate {\n"
"    background-color: #5e90fa;\n"
"    border: 1px solid #3874f2;\n"
"    image: url(qss:images/checkbox_indeterminate_light.png);\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Slider\n"
"==================================================================================================*/\n"
"QSlider,\n"
"QSlider:active,\n"
"QSlider:!active {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider:horizontal {\n"
"    padding: 0px 10px;\n"
"}\n"
"\n"
"QSlider:vertical {\n"
"    padding: 10px 0px;\n"
"}\n"
"\n"
"QSlider::groove {\n"
"    background-color: rgba(0,0,0,30);\n"
"    border: 1px solid rgba(0,0,0,40);\n"
"    border-radius: 5px;\n"
"    margin: 4px 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 8px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    width: 8px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled,\n"
"QSlider::groove:vertical:disabled {\n"
"    border-color:  #dcdcdc;\n"
"    background-color: #dcdcdc;\n"
"}\n"
"\n"
"QSlider::handle:horizontal,\n"
"QSlider::handle:vertical {\n"
"    background-color: #b6b6b6;\n"
"    border: 1px solid #b6b6b6;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    margin: -4px 0;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    margin: 0 -4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover,\n"
"QSlider::handle:horizontal:pressed,\n"
"QSlider::handle:vertical:pressed {\n"
"    border-color: #5e90fa;\n"
"    background-color: #5e90fa;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled,\n"
"QSlider::handle:vertical:disabled {\n"
"    border-color: #dcdcdc;\n"
"    background-color: #dcdcdc;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Toolbar buttons\n"
"==================================================================================================*/\n"
"/*QToolBar > QComboBox,   disabled because creates different margins for body and drop-down button */\n"
"QToolBar > QAbstractSpinBox,\n"
"QToolBar > QSpinBox,\n"
"QToolBar > QDoubleSpinBox,\n"
"QToolBar > QLineEdit,\n"
"QToolBar > QTextEdit,\n"
"QToolBar > QTimeEdit,\n"
"QToolBar > QDateEdit,\n"
"QToolBar > QDateTimeEdit {\n"
"    margin: 0px 2px;\n"
"    padding: 0px;\n"
"    min-width: 70px; /* necessary to show its content */\n"
"}\n"
"\n"
"QToolBar > QComboBox,\n"
"QToolBar > QAbstractSpinBox,\n"
"QToolBar > QSpinBox,\n"
"QToolBar > QDoubleSpinBox,\n"
"QToolBar > QLineEdit,\n"
"QToolBar > QTextEdit,\n"
"QToolBar > QTimeEdit,\n"
"QToolBar > QDateEdit,\n"
"QToolBar > QDateTimeEdit {\n"
"    min-height: 0px; /* reset it inside Tool Bar due to the user ability to set the \"size of toolbar icons\" inside Preferences  */\n"
"}\n"
"\n"
"QToolBar > QPushButton {\n"
"    padding: 0px;\n"
"    margin: 1px; /* doesn\'t work with :left, :right:, :top or :bottom sub-controls */\n"
"    min-width: 16px; /* could not be larger due to switchable Preferences \"Size of toolbar icons\" */\n"
"    min-height: 16px; /* could not be larger due to switchable Preferences \"Size of toolbar icons\" */\n"
"    border-radius: 4px; /* same as regular QPushButton */\n"
"}\n"
"\n"
"QToolBar > QPushButton:checked {\n"
"    border: 1px solid #7cabf9;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #cbd8e6, stop:1 #7cabf9);\n"
"}\n"
"\n"
"QToolBar > QPushButton:!checked {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.3, x2:0, y2:1, stop:0 #f5f5f5, stop:1 #e6e6e6);\n"
"    border: 1px solid #d2d2d2;\n"
"    border-bottom-color: #c3c3c3; /* simulates shadow under the button */\n"
"}\n"
"\n"
"QToolBar > QPushButton:checked:hover {\n"
"    border-color: #6f9efa;\n"
"}\n"
"\n"
"QToolBar > QPushButton:!checked:hover {\n"
"    color: black;\n"
"    border-color: #b6b6b6;\n"
"}\n"
"\n"
"QToolBar > QPushButton:checked:pressed {\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
"QToolBar > QPushButton:!checked:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #b6b6b6, stop:1 #e6e6e6);\n"
"}\n"
"\n"
"QToolBar > QPushButton:checked:disabled,\n"
"QToolBar > QPushButton:!checked:disabled {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolBar > QToolButton {\n"
"    margin: 2px;\n"
"    padding: 2px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QToolBar > QToolButton:hover {\n"
"    background-color: rgba(0,0,0,20);\n"
"}\n"
"\n"
"QToolBar > QToolButton:pressed {\n"
"    background-color: rgba(0,0,0,30);\n"
"}\n"
"\n"
"/* ToolBar menu buttons (buttons with drop-down menu) */\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton {\n"
"    padding-right: 20px; /* Hack to add more width to buttons with menu */\n"
"    border: 1px solid transparent;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton:hover,\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton:pressed,\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton:open {\n"
"    border: 1px solid #7cabf9;\n"
"}\n"
"\n"
"QToolBar QToolButton::menu-button,\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton::menu-button {\n"
"    border: none;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    width: 16px; /* 16px width + 4px for border = 20px allocated above */\n"
"    outline: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton::menu-button:hover,\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton::menu-button:pressed,\n"
"QToolBar > QToolButton#qt_toolbutton_menubutton::menu-button:open {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9);\n"
"}\n"
"\n"
"QToolBar > QToolButton::menu-arrow {\n"
"    background-image: url(qss:images/down_arrow_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    height: 10px; /* same as arrow image */\n"
"}\n"
"\n"
"QToolBar > QToolButton::menu-arrow:hover {\n"
"    background-image: url(qss:images/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QToolBar > QToolButton::menu-arrow:open {\n"
"    background-image: url(qss:images/down_arrow_lighter.png);\n"
"}\n"
"\n"
"/* when QToolButton is checked: */\n"
"QToolButton:checked {\n"
"    border: 1px solid #7cabf9;\n"
"    background-color: rgba(124,171,249,60); /* transparency for #7cabf9 color */\n"
"}\n"
"\n"
"QToolButton:checked:hover {\n"
"    border: 1px solid #7cabf9;\n"
"    background-color: rgba(124,171,249,80); /* transparency for #7cabf9 color */\n"
"}\n"
"\n"
"/*The \"show more\" button  (it can also be stylable with \"QToolBarExtension\" */\n"
"QToolBar QToolButton#qt_toolbar_ext_button {\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    /*background-image: url(qss:images/more_dark.png);*/\n"
"    image: transparent;\n"
"    background-repeat: none;\n"
"    background-position: center left;\n"
"}\n"
"\n"
"QToolBar QToolButton#qt_toolbar_ext_button:hover {\n"
"    /*background-image: url(qss:images/more_light.png);*/\n"
"    border-color: #e0e0e0;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"QToolBar QToolButton#qt_toolbar_ext_button:on {\n"
"    /*background-image: url(qss:images/more_light.png);*/\n"
"    border-color: #e0e0e0;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"Tables (spreadsheets)\n"
"==================================================================================================*/\n"
"QTableView {\n"
"    gridline-color: #d2d2d2;\n"
"    selection-color: #1b3774;\n"
"    selection-background-color: #cbd8e6;\n"
"}\n"
"\n"
"QTableView::item:hover  {\n"
"    background-color: rgba(0,0,0,10);  /* temporal: is it displayed in Linux or Windows? on OSX it isn\'t */\n"
"}\n"
"\n"
"QTableView::item:disabled  {\n"
"    color: #e6e6e6;\n"
"}\n"
"\n"
"QTableView::item:selected  {\n"
"    color: #1b3774;\n"
"    border-color: #cbd8e6; /* same as focused background color */\n"
"    border-bottom-color: #7cabf9; /* same as focused border color */\n"
"}\n"
"\n"
"/* fix for elements inside the cells */\n"
"QTableView > QWidget > QComboBox,\n"
"QTableView > QWidget > QAbstractSpinBox,\n"
"QTableView > QWidget > QSpinBox,\n"
"QTableView > QWidget > QDoubleSpinBox,\n"
"QTableView > QWidget > QLineEdit,\n"
"QTableView > QWidget > QTextEdit,\n"
"QTableView > QWidget > QTimeEdit,\n"
"QTableView > QWidget > QDateEdit,\n"
"QTableView > QWidget > QDateTimeEdit,\n"
"QTableView > QWidget > QComboBox:drop-down,\n"
"QTableView > QWidget > QAbstractSpinBox:up-button,\n"
"QTableView > QWidget > QSpinBox:up-button,\n"
"QTableView > QWidget > QDoubleSpinBox:up-button,\n"
"QTableView > QWidget > QTimeEdit:up-button,\n"
"QTableView > QWidget > QDateEdit:up-button,\n"
"QTableView > QWidget > QDateTimeEdit:up-button,\n"
"QTableView > QWidget > QAbstractSpinBox:down-button,\n"
"QTableView > QWidget > QSpinBox:down-button,\n"
"QTableView > QWidget > QDoubleSpinBox:down-button,\n"
"QTableView > QWidget > QTimeEdit:down-button,\n"
"QTableView > QWidget > QDateEdit:down-button,\n"
"QTableView > QWidget > QDateTimeEdit:down-button,\n"
"QTableView > QWidget > Gui--ColorButton {\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTableView > QWidget > QComboBox,\n"
"QTableView > QWidget > QAbstractSpinBox,\n"
"QTableView > QWidget > QSpinBox,\n"
"QTableView > QWidget > QDoubleSpinBox,\n"
"QTableView > QWidget > QLineEdit,\n"
"QTableView > QWidget > QTextEdit,\n"
"QTableView > QWidget > QTimeEdit,\n"
"QTableView > QWidget > QDateEdit,\n"
"QTableView > QWidget > QDateTimeEdit {\n"
"    color: black;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QTableView > QWidget > QComboBox:drop-down,\n"
"QTableView > QWidget > QAbstractSpinBox:up-button,\n"
"QTableView > QWidget > QSpinBox:up-button,\n"
"QTableView > QWidget > QDoubleSpinBox:up-button,\n"
"QTableView > QWidget > QTimeEdit:up-button,\n"
"QTableView > QWidget > QDateEdit:up-button,\n"
"QTableView > QWidget > QDateTimeEdit:up-button,\n"
"QTableView > QWidget > QAbstractSpinBox:down-button,\n"
"QTableView > QWidget > QSpinBox:down-button,\n"
"QTableView > QWidget > QDoubleSpinBox:down-button,\n"
"QTableView > QWidget > QTimeEdit:down-button,\n"
"QTableView > QWidget > QDateEdit:down-button,\n"
"QTableView > QWidget > QDateTimeEdit:down-button,\n"
"QTableView > QWidget > Gui--ColorButton {\n"
"    background-color: rgba(0,0,0,30);\n"
"}\n"
"\n"
"QTableView > QWidget > QComboBox:focus,\n"
"QTableView > QWidget > QAbstractSpinBox:focus,\n"
"QTableView > QWidget > QSpinBox:focus,\n"
"QTableView > QWidget > QDoubleSpinBox:focus,\n"
"QTableView > QWidget > QLineEdit:focus,\n"
"QTableView > QWidget > QTextEdit:focus,\n"
"QTableView > QWidget > QTimeEdit:focus,\n"
"QTableView > QWidget > QDateEdit:focus,\n"
"QTableView > QWidget > QDateTimeEdit:focus {\n"
"    color: #1b3774;\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"    border-color: #cbd8e6;\n"
"    background-color: #cbd8e6;\n"
"}\n"
"\n"
"QTableView > QWidget > QComboBox:disabled,\n"
"QTableView > QWidget > QAbstractSpinBox:disabled,\n"
"QTableView > QWidget > QSpinBox:disabled,\n"
"QTableView > QWidget > QDoubleSpinBox:disabled,\n"
"QTableView > QWidget > QLineEdit:disabled,\n"
"QTableView > QWidget > QTextEdit:disabled,\n"
"QTableView > QWidget > QTimeEdit:disabled,\n"
"QTableView > QWidget > QDateEdit:disabled,\n"
"QTableView > QWidget > QDateTimeEdit:disabled {\n"
"    color: rgba(0,0,0,120);\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QTableView > QWidget > QComboBox:read-only,\n"
"QTableView > QWidget > QAbstractSpinBox:read-only,\n"
"QTableView > QWidget > QSpinBox:read-only,\n"
"QTableView > QWidget > QDoubleSpinBox:read-only,\n"
"QTableView > QWidget > QLineEdit:read-only,\n"
"QTableView > QWidget > QTextEdit:read-only,\n"
"QTableView > QWidget > QTimeEdit:read-only,\n"
"QTableView > QWidget > QDateEdit:read-only,\n"
"QTableView > QWidget > QDateTimeEdit:read-only {\n"
"    color: black;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"\n"
"/*==================================================================================================\n"
"EXPERIMENTAL\n"
"==================================================================================================*/\n"
"\n"
"/* Fix for preventing elements in different rows to accidentaly overlap */\n"
"QDialog QGroupBox QFrame {\n"
"    margin: 2px 0px;\n"
"}\n"
"\n"
"*[mandatoryField=\"true\"] { background-color: cyan }\n"
"QPushButton {\n"
"    border-radius: 20px;\n"
"    color: rgb(230, 230, 230);\n"
"    text-align: center;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5e90fa, stop:1 #3874f2);\n"
"    border: 1px solid #d2d2d2;\n"
"    border-bottom-color: #c3c3c3; /* simulates shadow under the button */\n"
"    padding: 4px 22px;\n"
"    margin: 4px 4px;\n"
"    min-height: 16px; /* same as QTabBar QPushButton min-width */\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"    color: white;\n"
"    border: 1px solid rgb(49, 44, 113);\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.512438 rgba(69, 124, 225, 255), stop:1 rgba(82, 157, 255, 255))\n"
"}\n"
"\n"
"QPushButton:disabled,\n"
"QPushButton:disabled:checked {\n"
"    color: #b6b6b6;\n"
"    border-color: #e6e6e6;\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(35, 72, 147);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"/* Color Buttons */\n"
"Gui--ColorButton,\n"
"Gui--ColorButton:disabled {\n"
"    padding: 0px; /* reset */\n"
"    margin: 0px; /* reset */\n"
"}\n"
"\n"
"Gui--ColorButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.3, x2:0, y2:1, stop:0 #f5f5f5, stop:1 #e6e6e6);\n"
"    border: 1px solid #d2d2d2;\n"
"    border-bottom-color: #c3c3c3; /* simulates shadow under the button */\n"
"}\n"
"\n"
"Gui--ColorButton:disabled {\n"
"    border-color: transparent;\n"
"    background-color: rgba(0,0,0,10);\n"
"}\n"
"\n"
"Gui--ColorButton:hover,\n"
"Gui--ColorButton:focus {\n"
"    border-color: #3874f2;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5e90fa, stop:1 #3874f2);\n"
"}\n"
"\n"
"Gui--ColorButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"/* Pushbutton style for \"...\" inside Placement cell which launches Placement tool */\n"
"Gui--PropertyEditor--PropertyEditor > QWidget > QWidget > QPushButton {\n"
"    background-color: #b6b6b6;\n"
"    border: 1px solid #828282;\n"
"    min-width: 16px; /* reset it due to larger value on regular QPushButton, same or bigger value as regular QPushButton min-height */\n"
"    border-radius: 0px;\n"
"    margin: 0px; /* reset */\n"
"    padding: 0px; /* reset */\n"
"}\n"
"\n"
"/* Fix for Expressions description QFrame that is \"broken\" with initial reset */\n"
"Gui--PropertyEditor--PropertyEditor > QWidget > QWidget > QWidget > QWidget > QFrame {\n"
"    background-color: #f5f5f5; /* main background color */\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 2px;\n"
"    padding: 2px 6px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #5e90fa;\n"
"    border-color: #3874f2;\n"
"}")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(1, 10, 651, 621))
        self.tabWidget.setObjectName("tabWidget")
        # self.tab = QtWidgets.QWidget()
        # self.tab.setObjectName("tab")
        # self.listWidget = QtWidgets.QListWidget(self.tab)
        # self.listWidget.setGeometry(QtCore.QRect(0, 10, 641, 431))
        # font = QtGui.QFont()
        # font.setPointSize(11)
        # self.listWidget.setFont(font)
        # self.listWidget.setObjectName("listWidget")
        # item = QtWidgets.QListWidgetItem()
        # self.listWidget.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.listWidget.addItem(item)
        # self.pushButton = QtWidgets.QPushButton(self.tab)
        # self.pushButton.setGeometry(QtCore.QRect(120, 450, 401, 71))
        # font = QtGui.QFont()
        # font.setFamily("Segoe UI")
        # font.setPointSize(16)
        # self.pushButton.setFont(font)
        # self.pushButton.setObjectName("pushButton")
        # self.tabWidget.addTab(self.tab, "")
        # self.tab_2 = QtWidgets.QWidget()
        # self.tab_2.setObjectName("tab_2")
        # self.tabWidget.addTab(self.tab_2, "")
        #
        # self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # __sortingEnabled = self.listWidget.isSortingEnabled()
        # self.listWidget.setSortingEnabled(False)
        # item = self.listWidget.item(0)
        # item.setText(_translate("Dialog", "New Item"))
        # item = self.listWidget.item(1)
        # item.setText(_translate("Dialog", "New Item"))
        # self.listWidget.setSortingEnabled(__sortingEnabled)
        # self.pushButton.setText(_translate("Dialog", "تطبيق"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
